# import = ["~/c/sesh/sesh.toml"]
[default_session]
startup_command = "nvim +GoToFile"

# [[session]]
# name = "spotify"
# path = "~/git_repos/dotfiles/spotify-player"
# startup_script = "~/git_repos/dotfiles/sesh/bin/spotify.sh"

[[session]]
name = "Home 🏡"
path = "~/"

[[session]]
name = "Code 💻"
path = "~/repos"
startup_command = "l"

[[session]]
name = "tmux config"
path = "~/repos/dotfiles/.config/tmux"
# tmuxp = "~/c/dotfiles/.config/tmux/tmuxp-tmux.yml"
# tmuxp = "/Users/joshmedeski/c/dotfiles/.config/tmux/tmuxp-tmux.yml"
startup_command = "nvim tmux.conf"

[[session]]
name = "gitmux config"
path = "~/repos/dotfiles/.config/tmux"
startup_command = "nvim gitmux.conf"

# [[session]]
# TODO: update the name fo the session to "update done ✅" when the u script ends
# name = "update" 
# path = "~/c/dotfiles"
# startup_command = "u"
# TODO: implement "detatched feature"
# detached = true # never attach to this session, just create it in the background

[[session]]
name = "neovim config"
path = "~/repos/dotfiles/.config/nvim"

[[session]]
name = "fish config"
path = "~/repos/dotfiles/.config/fish"
startup_command = "nvim config.fish"

[[session]]
name = "yazi config"
path = "~/repos/dotfiles/.config/yazi"
startup_command = "nvim yazi.toml"

[[session]]
name = "wezterm config"
path = "~/repos/dotfiles/.config/wezterm"
startup_command = "nvim wezterm.lua"

# [[session]]
# name = "nutiliti new worktree"
# path = "~/repos/nu"
# # TODO: auto-close this session when the worktree has been created successfully?  
# # TODO: append [[session]] ./nu/{name}/package/* to this config for dev mode bonus
# startup_commad = "nu_new_worktree"

# [[session]]
# name = "second brain 🧠"
# path = "~/c/second-brain"
# startup_command = "nvim +ObsidianToday"

[[session]]
name = "sesh config"
path = "~/repos/dotfiles/.config/sesh"
startup_command = "nvim sesh.toml"

[[session]]
name = "my custom binaries"
path = "~/repos/dotfiles/.config/bin"

[[session]]
name = "dotfiles"
path = "~/repos/dotfiles"
startup_command = "lazygit"
# startup_command = "u"

[[session]]
name = "tmux-fzf-url 🖇️"
path = "~/.config/tmux/plugins/tmux-fzf-url"
startup_command = "nvim fzf-url.sh"

[[session]]
name = "Downloads 📥"
path = "~/Downloads"
startup_command = "yazi"
